---
apiVersion: v1
kind: Service
metadata:
  name: upstream-pve-backend-svc
  namespace: routing-mesh
spec:
  ports:
    - name: https # Renamed to explicitly signal the intent
      port: 443   # The logical routing port for the service
      targetPort: 8006 # Map logical service port 443 to the physical 8006 backend
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: upstream-pve-backend-slice
  namespace: routing-mesh
  labels:
    kubernetes.io/service-name: upstream-pve-backend-svc
addressType: IPv4
ports:
  - name: https
    port: 8006
endpoints:
  - addresses:
      - "192.168.68.2"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pve-upstream-route
  namespace: routing-mesh
spec:
  parentRefs:
    - name: edge-gateway
      namespace: routing-mesh
  hostnames:
    - "upstream.datakube.org"
  rules:
    - backendRefs:
        - name: upstream-pve-backend-svc
          port: 443
