apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-gateway-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/abaas-madscience/home-tls-gateway.git' 
    targetRevision: HEAD
    path: apps/gateway-stack
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
