apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: 'https://github.com/abaas-madscience/home-tls-gateway.git'
    targetRevision: HEAD
    path: infrastructure/metallb
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
